name: anchore-analysis

env:
  DOCKER_IMAGE_NAME: webdevsvc/jaegertracing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  anchore-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2.3.2
      - name: Build the Docker image
        uses: docker/build-push-action@v2.0.1
        with:
          push: false
          repository: ${{ env.DOCKER_IMAGE_NAME }}
          tags: latest
      - name: Perform Anchore analysis
        uses: anchore/scan-action@master
        with:
          acs-report-enable: true
          dockerfile-path: Dockerfile
          image-reference: ${{ env.DOCKER_IMAGE_NAME }}:latest
      - name: Upload Anchore report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
